development:
  database: heroku_app935150
  host: dbh43.mongolab.com
  port: 27437
  username: heroku_app935150
  password: 898aqg2mtdlas7ihq55dfki2u7
  websocket_channel: magent.websocket

test:
  database: heroku_app935150

production:
  database: heroku_app935150
  websocket_channel: magent.websocket
