defaults: &defaults
  host: localhost
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3

development:
  <<: *defaults
  database: shapado-development
  uri: <%= ENV['MONGOLAB_URI'] %>

test:
  <<: *defaults
  database: shapado-test
  uri: <%= ENV['MONGOLAB_URI'] %>

production:
  <<: *defaults
  database: shapado-production
  uri: <%= ENV['MONGOLAB_URI'] %>