base: &common
  site: http://AskItAnswerIt.herokuapp.com
  analytics_id: UA-10385211-1
  analytics_vendor: googlean
  session_key: _shapado_session
  session_secret: 9ac4fd97a52153070a0bd47467c00eded1badf526f145827384ddfde45ac0bfd3f0230c961ddfb9ef84d490b3d889e0169de8eee3ef7b7ed114262824f8aa8aa
  rest_auth_key: b4d66d73a1ade79ce227fba01b33f2ab021888ef
  rest_auth_digest_stretches: 10
  enable_sharing: true
  notification_email: malligarjunan@gmail.com
  default_language: en
  application_name: AskItAnswerIt.herokuapp
  is_shapadocom: false
  enable_groups: false
  default_language: en
  enable_i18n: false
  default_timezone: "Tokyo"
  ssl: false
  googl_api_key: YOUR_GOOGL_API_KEY_HERE

  smtp:
    activate: true
    server: "smtp.gmail.com"
    port: 587
    domain: "gmail.com"
    login: "malligarjunan@gmail.com"
    password: "sankar1982"

  facebook:
    activate: false
    key: facebook api key
    secret: facebook secret key

  twitter:
    activate: false
    key: twitter api key
    secret: twitter secret key

  mailing:
    activate: false
    user: app

  recaptcha:
    activate: true
    public_key: your public key
    private_key: your private key

  exception_notification:
    activate: true
    exception_sender_address: malligarjunan@gmail.com
    exception_recipients:
    - malligarjunan@gmail.com
    - smalligarjunan@yahoo.com

development:
  <<: *common
  domain: AskItAnswerIt.herokuapp.com
production:
  <<: *common
  domain: AskItAnswerIt.herokuapp.com
  googlean_domain: .gmail.com
test:
  <<: *common
  domain: test.loc

